# Generated by Django 5.1.3 on 2025-01-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_produk_remove_productimage_no_produk_gambarproduk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='no_produk',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
