# Generated by Django 5.1.3 on 2025-01-25 17:24

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_produk_no_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambarproduk',
            name='path_gambar',
            field=models.ImageField(upload_to=backend.models.GambarProduk.upload_to_products),
        ),
    ]
