# Generated by Django 5.1.3 on 2025-02-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_kategori_produk_deskripsi_alter_produk_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
